[package]
name = "brezn"
version = "0.1.0"
edition = "2021"

[lib]
name = "brezn"
crate-type = ["cdylib", "staticlib", "rlib"]

[[bin]]
name = "brezn-server"
path = "src/main.rs"

[[bin]]
name = "brezn-cli"
path = "src/bin/cli.rs"

[dependencies]
rusqlite = { version = "0.31", features = ["bundled"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
ring = "0.17"
sodiumoxide = "0.2"
tokio = { version = "1.0", features = ["full"] }
uuid = { version = "1.0", features = ["v4"] }
chrono = { version = "0.4", features = ["serde"] }
anyhow = "1.0"
thiserror = "1.0"
actix-web = "4.4"
qrcode = "0.13"
image = "0.24"
base64 = "0.21"
bardecoder = "0.4"
hex = "0.4"
get-if-addrs = "0.10"

[dev-dependencies]
rand = "0.8"

