name: 🤖 AI Development Agent - Brezn MVP

# Läuft kontinuierlich - ein Agent wartet auf den anderen
on:
  workflow_dispatch:  # Manueller Start
  push:
    branches: [ main, develop, 'ai-feature/**' ]  # Läuft auf main UND Feature Branches
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '.github/**'
  # Automatischer Start bei jedem Push - Agenten laufen kontinuierlich

# Verhindert parallele Ausführung - nur ein Agent gleichzeitig
concurrency:
  group: ai-agent-chain
  cancel-in-progress: false

jobs:
  ai-development:
    name: 🤖 AI Agent Development
    runs-on: ubuntu-latest
    
    # Umgebungsvariablen für AI Agent
    env:
      RUST_BACKTRACE: 1
      CARGO_TERM_COLOR: always
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    steps:
      - name: 📥 Repository auschecken
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Vollständige Git-Historie für AI-Analyse
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: 🔍 Projektstatus analysieren
        id: analyze
        run: |
          echo "🤖 Analysiere Brezn Projektstatus..."
          
          # MVP-Fortschritt berechnen
          TOTAL_FEATURES=10
          COMPLETED_FEATURES=$(find src -name "*.rs" -exec grep -l "impl.*Peer\|impl.*Tor\|impl.*QR" {} \; | wc -l)
          MVP_PROGRESS=$((COMPLETED_FEATURES * 100 / TOTAL_FEATURES))
          
          echo "📊 MVP-Fortschritt: ${MVP_PROGRESS}%"
          echo "✅ Abgeschlossene Features: ${COMPLETED_FEATURES}/${TOTAL_FEATURES}"
          
          # Nächste Features identifizieren
          if [ $MVP_PROGRESS -lt 50 ]; then
            NEXT_FEATURE="p2p-peer-discovery"
            PRIORITY="high"
          elif [ $MVP_PROGRESS -lt 70 ]; then
            NEXT_FEATURE="tor-integration"
            PRIORITY="medium"
          else
            NEXT_FEATURE="qr-code-implementation"
            PRIORITY="low"
          fi
          
          echo "🎯 Nächstes Feature: ${NEXT_FEATURE}"
          echo "⚡ Priorität: ${PRIORITY}"
          
          # Output für nächste Steps
          echo "mvp_progress=${MVP_PROGRESS}" >> $GITHUB_OUTPUT
          echo "next_feature=${NEXT_FEATURE}" >> $GITHUB_OUTPUT
          echo "priority=${PRIORITY}" >> $GITHUB_OUTPUT
      
      - name: 🐍 Python Setup
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
      
      - name: 📦 Python Dependencies installieren
        run: |
          python -m pip install --upgrade pip
          pip install pathlib typing-extensions
      
      - name: 🤖 AI Agent starten
        id: ai_agent
        run: |
          echo "🤖 Starte Brezn AI Development Agent..."
          
          # AI Agent ausführbar machen
          chmod +x .github/scripts/ai_agent.py
          
          # AI Agent ausführen
          python .github/scripts/ai_agent.py
          
          # Ausgabe für nächste Steps
          echo "ai_agent_completed=true" >> $GITHUB_OUTPUT
          echo "implementation_success=true" >> $GITHUB_OUTPUT
      
      - name: 🔍 Feature Branch Status prüfen
        id: check_branch
        run: |
          echo "🔍 Prüfe Feature Branch Status..."
          
          FEATURE_NAME="${{ steps.analyze.outputs.next_feature }}"
          
          # Suche nach existierenden Feature Branches
          EXISTING_BRANCHES=$(git branch -r | grep "ai-feature/${FEATURE_NAME}" | head -1 | sed 's/origin\///')
          
          if [ -n "$EXISTING_BRANCHES" ]; then
            echo "🔄 Existierender Feature Branch gefunden: ${EXISTING_BRANCHES}"
            echo "branch_exists=true" >> $GITHUB_OUTPUT
            echo "existing_branch=${EXISTING_BRANCHES}" >> $GITHUB_OUTPUT
            
            # Branch auschecken
            git checkout -b "${EXISTING_BRANCHES}" origin/"${EXISTING_BRANCHES}"
            echo "✅ Auf existierendem Branch weitergearbeitet: ${EXISTING_BRANCHES}"
          else
            echo "🆕 Erstelle neuen Feature Branch..."
            echo "branch_exists=false" >> $GITHUB_OUTPUT
            
            # Neuen Branch erstellen
            BRANCH_NAME="ai-feature/${FEATURE_NAME}-$(date +%Y%m%d-%H%M)"
            git checkout -b "$BRANCH_NAME"
            echo "branch_name=${BRANCH_NAME}" >> $GITHUB_OUTPUT
            echo "✅ Neuer Feature Branch erstellt: ${BRANCH_NAME}"
          fi
      
      - name: 🔧 Feature implementieren
        id: implement
        run: |
          echo "🔧 Feature wurde bereits vom AI Agenten implementiert..."
          
          # Branch pushen
          if [ "${{ steps.check_branch.outputs.branch_exists }}" == "true" ]; then
            BRANCH_NAME="${{ steps.check_branch.outputs.existing_branch }}"
          else
            BRANCH_NAME="${{ steps.check_branch.outputs.branch_name }}"
          fi
          
          git push origin "$BRANCH_NAME"
          echo "branch_name=${BRANCH_NAME}" >> $GITHUB_OUTPUT
      
      - name: 🔄 Pull Request erstellen
        run: |
          echo "🔄 Pull Request wird vom AI Agenten erstellt..."
          echo "Der AI Agent kümmert sich um alle Details"
      
      - name: 📊 Entwicklung-Status aktualisieren
        run: |
          echo "📊 Entwicklung-Status wird vom AI Agenten aktualisiert..."
          echo "Der AI Agent kümmert sich um alle Details"
      
      - name: 🔄 Nächsten Agenten starten
        if: success()
        run: |
          echo "🔄 Starte nächsten Agenten in der Kette..."
          
          # GitHub API verwenden um nächsten Workflow zu starten
          FEATURE_NAME="${{ steps.analyze.outputs.next_feature }}"
          BRANCH_NAME="${{ steps.implement.outputs.branch_name }}"
          
          # Prüfe ob Feature vollständig implementiert ist
          if [ "${{ steps.ai_agent.outputs.implementation_success }}" == "true" ]; then
            echo "✅ Feature erfolgreich implementiert - nächster Agent startet automatisch"
            
            # Starte nächsten Workflow mit 30 Sekunden Verzögerung
            sleep 30
            
            # WICHTIG: Starte nächsten Workflow vom FEATURE BRANCH aus, nicht von main!
            gh workflow run ai-agent-development.yml --ref "$BRANCH_NAME"
            
            echo "🚀 Nächster Agent startet vom Feature Branch: $BRANCH_NAME"
          else
            echo "❌ Feature nicht vollständig - warte auf manuellen Start"
          fi
      
      - name: 🎉 Erfolg melden
        if: success()
        run: |
          echo "🎉 AI Agent erfolgreich abgeschlossen!"
          echo "📊 MVP-Fortschritt: ${{ steps.analyze.outputs.mvp_progress }}%"
          echo "🎯 Implementiertes Feature: ${{ steps.analyze.outputs.next_feature }}"
          echo "🌿 Feature Branch: ${{ steps.implement.outputs.branch_name }}"
          echo "🔄 Nächster Agent startet automatisch in 30 Sekunden..."
          echo "⏰ Kontinuierliche Entwicklung läuft..."
      
      - name: ❌ Fehler melden
        if: failure()
        run: |
          echo "❌ AI Agent fehlgeschlagen!"
          echo "🔍 Überprüfe die Logs für Details"
          echo "🔄 Agenten-Kette pausiert - manueller Start erforderlich"
          echo "📋 Feature Branch: ${{ steps.implement.outputs.branch_name || 'Unbekannt' }}"
