name: Build iOS Archive

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install CocoaPods
        run: sudo gem install cocoapods

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Add Rust iOS targets
        run: |
          rustup target add aarch64-apple-ios x86_64-apple-ios

      - name: Check for iOS project
        id: check-ios
        run: |
          if [ -d "brezn/mobile/ios" ] && [ -f "brezn/mobile/ios/Brezn.xcworkspace" ]; then
            echo "ios_exists=true" >> $GITHUB_OUTPUT
          else
            echo "ios_exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Build Rust libraries for iOS
        if: steps.check-ios.outputs.ios_exists == 'true'
        run: |
          cd brezn
          cargo build --target aarch64-apple-ios --release --lib --features mobile
          cargo build --target x86_64-apple-ios --release --lib --features mobile

      - name: Install mobile dependencies
        if: steps.check-ios.outputs.ios_exists == 'true'
        run: |
          cd brezn/mobile
          npm ci

      - name: Install Pods
        if: steps.check-ios.outputs.ios_exists == 'true'
        run: |
          cd brezn/mobile/ios
          pod install --repo-update

      - name: Build iOS archive
        if: steps.check-ios.outputs.ios_exists == 'true'
        run: |
          cd brezn/mobile/ios
          xcodebuild -workspace Brezn.xcworkspace \
            -scheme Brezn \
            -configuration Release \
            -archivePath build/Brezn.xcarchive \
            -destination "generic/platform=iOS" \
            archive

      - name: Upload iOS archive artifact
        if: steps.check-ios.outputs.ios_exists == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: brezn-ios-archive
          path: brezn/mobile/ios/build/Brezn.xcarchive

      - name: Skip - iOS project not present
        if: steps.check-ios.outputs.ios_exists == 'false'
        run: |
          echo "iOS project not found at brezn/mobile/ios. Commit the React Native iOS project and signing configuration to build IPAs." 
          exit 0