name: Performance Tests

on:
  workflow_dispatch:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  performance-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install cargo-criterion
        run: cargo install cargo-criterion

      - name: Run performance benchmarks
        run: |
          cd brezn
          cargo criterion --message-format=json > performance-results.json

      - name: Analyze performance results
        run: |
          python3 scripts/analyze_performance.py performance-results.json

      - name: Upload performance results
        uses: actions/upload-artifact@v4
        with:
          name: performance-results
          path: |
            performance-results.json
            performance-analysis.html

      - name: Comment PR with results
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const results = JSON.parse(fs.readFileSync('performance-results.json', 'utf8'));
            
            const comment = `## 📊 Performance Test Results
            
            **Build Time:** ${results.build_time}ms
            **Memory Usage:** ${results.memory_usage}MB
            **CPU Usage:** ${results.cpu_usage}%
            
            ${results.regressions > 0 ? '⚠️ **Performance regressions detected!**' : '✅ **No performance regressions**'}
            `;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });